In [1]:
import numpy as np
from pylab import plt
import utils
import utils.plt
from utils.__Timer__ import Timer
import pylab
pylab.ion()

In [2]:
def f(y,x,nRows,nCols):
    x0 = nCols/2
    y0 = nRows/2
    return (x-x0)**2+(y-y0)**2

In [3]:
# define image size:
nRows = 3000
nCols = 4000

### Suppose (x,y) stands for pixel locations, and we want to evaluate f on all pixels

In [4]:
# Here is the bad way to do it in Python
z1 = np.zeros((nRows,nCols))
timer1 = Timer()
timer1.tic()
for row in range(nRows):
    for col in range(nCols):
        z1[row,col]=f(y=row,x=col,nRows=nRows,nCols=nCols)
timer1.toc()
print(timer1)

Timer: secs = 16.4950106


In [5]:
yy,xx=np.mgrid[0:nRows,0:nCols]
print('xx:')
print(xx)
print('yy:')
print(yy)

xx:
[[   0    1    2 ... 3997 3998 3999]
 [   0    1    2 ... 3997 3998 3999]
 [   0    1    2 ... 3997 3998 3999]
 ...
 [   0    1    2 ... 3997 3998 3999]
 [   0    1    2 ... 3997 3998 3999]
 [   0    1    2 ... 3997 3998 3999]]
yy:
[[   0    0    0 ...    0    0    0]
 [   1    1    1 ...    1    1    1]
 [   2    2    2 ...    2    2    2]
 ...
 [2997 2997 2997 ... 2997 2997 2997]
 [2998 2998 2998 ... 2998 2998 2998]
 [2999 2999 2999 ... 2999 2999 2999]]


In [6]:
z2 = np.zeros((nRows,nCols))
timer2=Timer()
timer2.tic()
z2[:]=f(x=xx,y=yy,nRows=nRows,nCols=nCols)
# or even just:
#z2=f(x=xx,y=yy,nRows=nRows,nCols=nCols)
timer2.toc()
print(timer2)
print('speedup: ',timer1.secs/timer2.secs)
print(np.allclose(z1,z2))

Timer: secs = 0.34261530000000207
speedup:  48.14440744473438
True


In [7]:
timer3 = Timer()
timer3.tic()
z3 = np.fromfunction(f,shape=[nRows,nCols],nRows=nRows,nCols=nCols)
timer3.toc()
print('speedup: ',timer1.secs/timer3.secs)
print(np.allclose(z1,z3))

speedup:  48.161205480475715
True


In [8]:
pts = np.vstack([xx.ravel(),yy.ravel()]).T
print(pts.shape)
print('pts:')
print(pts)

(12000000, 2)
pts:
[[   0    0]
 [   1    0]
 [   2    0]
 ...
 [3997 2999]
 [3998 2999]
 [3999 2999]]


In [9]:
theta = np.deg2rad(30) # degrees to radians 
c = np.cos(theta)
s = np.sin(theta)
yy_new = c*xx-s*yy
xx_new = s*xx+c*yy

sl = slice(None,None,100)
# so xx[sl,sl] will be the same as xx[::100,::100] or the even more verbose xx[0:xx.shape[0]:100,0:xx.shape[1]:100]

In [ ]:
plt.plot(xx[sl,sl].ravel(),yy[sl,sl].ravel(),'r.')
plt.plot(z2, 'g.')
plt.plot(xx_new[sl,sl].ravel(),yy_new[sl,sl].ravel(),'b.')
plt.axis('equal')
plt.show()

In [ ]:
plt.plot(xx[sl,sl].ravel(),yy[sl,sl].ravel(),'r.')
plt.plot(xx_new[sl,sl].ravel(),yy_new[sl,sl].ravel(),'b.')
plt.axis('equal')
utils.plt.axis_ij()

In [ ]:
r = np.sqrt(z2)
plt.figure()
plt.subplot(121)
plt.imshow(z2)
plt.colorbar()
plt.set_cmap('jet')
plt.title('z')
plt.xticks([0,nCols/2,nCols])
plt.subplot(122)
plt.imshow(r)
plt.colorbar()
plt.set_cmap('jet')
plt.title('r')
plt.xticks([0,nCols/2,nCols])
plt.subplots_adjust(wspace=0.6)

In [ ]:
q = (r-r.min())/r.max()
labels = np.round(q*4).astype(np.int)
print(np.unique(labels))

In [ ]:
plt.imshow(labels)
plt.colorbar()
plt.set_cmap('gray')

In [ ]:
palette = np.array( [ [0,0,0],              # black
                    [255,0,0],              # red
                    [0,255,0],              # green
                    [0,0,255],              # blue
                    [255,255,255]           # white
                    ] )
print(palette.shape)
print(labels.shape)

In [ ]:
img = palette[labels]
print(img.shape)

In [ ]:
plt.imshow(img.astype(np.uint8))


In [ ]:
(np.arange(0,nCols,500))